/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CitationCalloutPastePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var CitationCalloutPastePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "paste-citation-callout",
      name: "Paste as Citation Callout",
      editorCallback: (editor, view) => {
        this.pasteAsCitationCallout(editor);
      }
    });
    this.addRibbonIcon("book", "Paste as Citation Callout", (evt) => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (activeView) {
        this.pasteAsCitationCallout(activeView.editor);
      }
    });
  }
  async pasteAsCitationCallout(editor) {
    try {
      let clipboardContent = "";
      let hasRichText = false;
      try {
        const clipboardItems = await navigator.clipboard.read();
        for (const clipboardItem of clipboardItems) {
          if (clipboardItem.types.includes("text/html")) {
            const htmlBlob = await clipboardItem.getType("text/html");
            const htmlText = await htmlBlob.text();
            clipboardContent = (0, import_obsidian.htmlToMarkdown)(htmlText);
            hasRichText = true;
            break;
          }
        }
      } catch (e) {
      }
      if (!hasRichText) {
        clipboardContent = await navigator.clipboard.readText();
      }
      if (!clipboardContent || clipboardContent.trim() === "") {
        new import_obsidian.Notice("Clipboard is empty");
        return;
      }
      const bookName = this.extractBookName(clipboardContent);
      const formattedContent = this.formatAsCitationCallout(clipboardContent, bookName);
      editor.replaceSelection(formattedContent);
      new import_obsidian.Notice(`Content pasted as Citation callout: ${bookName}`);
    } catch (error) {
      console.error("Error pasting Citation content:", error);
      new import_obsidian.Notice("Error accessing clipboard or formatting content");
    }
  }
  extractBookName(text) {
    const linkMatch = text.match(/\[([^\]]+)\]\([^)]*ref\.ly[^)]*\)/);
    if (linkMatch) {
      return linkMatch[1].replace(/_/g, "").trim();
    }
    const italicMatch = text.match(/\[_([^_]+)_\]/);
    if (italicMatch) {
      return italicMatch[1];
    }
    const lines = text.split("\n");
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i].trim();
      const authorBookMatch = line.match(/^([^,]+),\s+([^(]+)\s+\(/);
      if (authorBookMatch) {
        return authorBookMatch[2].trim();
      }
    }
    const italicBookMatch = text.match(/,\s+([^,]+?)\s+\(/);
    if (italicBookMatch) {
      const bookTitle = italicBookMatch[1].trim();
      if (bookTitle.split(" ").length > 1) {
        return bookTitle;
      }
    }
    const urlMatch = text.match(/https:\/\/ref\.ly\/logosres\/[^?]+/);
    if (urlMatch) {
      for (const line of lines) {
        if (line.includes("https://ref.ly/logosres")) {
          const titleMatch = line.match(/\[_([^_]+)_\]/);
          if (titleMatch) {
            return titleMatch[1];
          }
        }
      }
    }
    return "Logos Resource";
  }
  formatAsCitationCallout(content, bookName) {
    const lines = content.split("\n");
    const calloutLines = [`> [!Citation] ${bookName}`];
    for (const line of lines) {
      if (line.trim() === "") {
        calloutLines.push(">");
      } else {
        calloutLines.push(`> ${line}`);
      }
    }
    if (calloutLines.length > 1 && calloutLines[1] !== ">") {
      calloutLines.splice(1, 0, ">");
    }
    return calloutLines.join("\n");
  }
  onunload() {
  }
};

/* nosourcemap */